# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Binance

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BookTicker(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BookTicker()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBookTicker(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BookTicker
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BookTicker
    def UpdateId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BookTicker
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BookTicker
    def BestBid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BookTicker
    def BidQty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BookTicker
    def BestAsk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BookTicker
    def AskQty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BookTickerStart(builder):
    builder.StartObject(6)

def Start(builder):
    BookTickerStart(builder)

def BookTickerAddUpdateId(builder, updateId):
    builder.PrependUint64Slot(0, updateId, 0)

def AddUpdateId(builder, updateId):
    BookTickerAddUpdateId(builder, updateId)

def BookTickerAddSymbol(builder, symbol):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)

def AddSymbol(builder, symbol):
    BookTickerAddSymbol(builder, symbol)

def BookTickerAddBestBid(builder, bestBid):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bestBid), 0)

def AddBestBid(builder, bestBid):
    BookTickerAddBestBid(builder, bestBid)

def BookTickerAddBidQty(builder, bidQty):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bidQty), 0)

def AddBidQty(builder, bidQty):
    BookTickerAddBidQty(builder, bidQty)

def BookTickerAddBestAsk(builder, bestAsk):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(bestAsk), 0)

def AddBestAsk(builder, bestAsk):
    BookTickerAddBestAsk(builder, bestAsk)

def BookTickerAddAskQty(builder, askQty):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(askQty), 0)

def AddAskQty(builder, askQty):
    BookTickerAddAskQty(builder, askQty)

def BookTickerEnd(builder):
    return builder.EndObject()

def End(builder):
    return BookTickerEnd(builder)
