# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Binance

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Kline(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Kline()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKline(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Kline
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Kline
    def OpenTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Kline
    def OpenPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def HighPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def LowPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def ClosePrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def CloseTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Kline
    def QuoteAssetVolume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def NumberOfTrades(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Kline
    def TakerBuyBase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def TakerBuyQuote(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Kline
    def Ignore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def KlineStart(builder):
    builder.StartObject(12)

def Start(builder):
    KlineStart(builder)

def KlineAddOpenTime(builder, openTime):
    builder.PrependUint64Slot(0, openTime, 0)

def AddOpenTime(builder, openTime):
    KlineAddOpenTime(builder, openTime)

def KlineAddOpenPrice(builder, openPrice):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(openPrice), 0)

def AddOpenPrice(builder, openPrice):
    KlineAddOpenPrice(builder, openPrice)

def KlineAddHighPrice(builder, highPrice):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(highPrice), 0)

def AddHighPrice(builder, highPrice):
    KlineAddHighPrice(builder, highPrice)

def KlineAddLowPrice(builder, lowPrice):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(lowPrice), 0)

def AddLowPrice(builder, lowPrice):
    KlineAddLowPrice(builder, lowPrice)

def KlineAddClosePrice(builder, closePrice):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(closePrice), 0)

def AddClosePrice(builder, closePrice):
    KlineAddClosePrice(builder, closePrice)

def KlineAddVolume(builder, volume):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(volume), 0)

def AddVolume(builder, volume):
    KlineAddVolume(builder, volume)

def KlineAddCloseTime(builder, closeTime):
    builder.PrependUint64Slot(6, closeTime, 0)

def AddCloseTime(builder, closeTime):
    KlineAddCloseTime(builder, closeTime)

def KlineAddQuoteAssetVolume(builder, quoteAssetVolume):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(quoteAssetVolume), 0)

def AddQuoteAssetVolume(builder, quoteAssetVolume):
    KlineAddQuoteAssetVolume(builder, quoteAssetVolume)

def KlineAddNumberOfTrades(builder, numberOfTrades):
    builder.PrependUint64Slot(8, numberOfTrades, 0)

def AddNumberOfTrades(builder, numberOfTrades):
    KlineAddNumberOfTrades(builder, numberOfTrades)

def KlineAddTakerBuyBase(builder, takerBuyBase):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(takerBuyBase), 0)

def AddTakerBuyBase(builder, takerBuyBase):
    KlineAddTakerBuyBase(builder, takerBuyBase)

def KlineAddTakerBuyQuote(builder, takerBuyQuote):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(takerBuyQuote), 0)

def AddTakerBuyQuote(builder, takerBuyQuote):
    KlineAddTakerBuyQuote(builder, takerBuyQuote)

def KlineAddIgnore(builder, ignore):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(ignore), 0)

def AddIgnore(builder, ignore):
    KlineAddIgnore(builder, ignore)

def KlineEnd(builder):
    return builder.EndObject()

def End(builder):
    return KlineEnd(builder)
