# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Binance

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Klines(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Klines()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKlines(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Klines
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Klines
    def Klines(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Binance.Kline import Kline
            obj = Kline()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Klines
    def KlinesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Klines
    def KlinesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def KlinesStart(builder):
    builder.StartObject(1)

def Start(builder):
    KlinesStart(builder)

def KlinesAddKlines(builder, klines):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(klines), 0)

def AddKlines(builder, klines):
    KlinesAddKlines(builder, klines)

def KlinesStartKlinesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartKlinesVector(builder, numElems):
    return KlinesStartKlinesVector(builder, numElems)

def KlinesEnd(builder):
    return builder.EndObject()

def End(builder):
    return KlinesEnd(builder)
